apiVersion: apps/v1
kind: Deployment
metadata:
  name: converto-saas
  labels:
    app: converto-saas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: converto-saas
  template:
    metadata:
      labels:
        app: converto-saas
    spec:
      containers:
      - name: converto-saas
        image: converto-saas:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: converto-saas-service
spec:
  selector:
    app: converto-saas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
